/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSecurityRouteImport } from './routes/services.security'
import { Route as ServicesPlumbingRouteImport } from './routes/services.plumbing'
import { Route as ServicesLightingRouteImport } from './routes/services.lighting'
import { Route as ServicesHvacRouteImport } from './routes/services.hvac'
import { Route as ServicesEnergyHarvestingRouteImport } from './routes/services.energy-harvesting'
import { Route as ServicesEnergyAuditRouteImport } from './routes/services.energy-audit'
import { Route as ServicesElectricalRouteImport } from './routes/services.electrical'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSecurityRoute = ServicesSecurityRouteImport.update({
  id: '/services/security',
  path: '/services/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlumbingRoute = ServicesPlumbingRouteImport.update({
  id: '/services/plumbing',
  path: '/services/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLightingRoute = ServicesLightingRouteImport.update({
  id: '/services/lighting',
  path: '/services/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHvacRoute = ServicesHvacRouteImport.update({
  id: '/services/hvac',
  path: '/services/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEnergyHarvestingRoute =
  ServicesEnergyHarvestingRouteImport.update({
    id: '/services/energy-harvesting',
    path: '/services/energy-harvesting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEnergyAuditRoute = ServicesEnergyAuditRouteImport.update({
  id: '/services/energy-audit',
  path: '/services/energy-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesElectricalRoute = ServicesElectricalRouteImport.update({
  id: '/services/electrical',
  path: '/services/electrical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services/electrical': typeof ServicesElectricalRoute
  '/services/energy-audit': typeof ServicesEnergyAuditRoute
  '/services/energy-harvesting': typeof ServicesEnergyHarvestingRoute
  '/services/hvac': typeof ServicesHvacRoute
  '/services/lighting': typeof ServicesLightingRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/security': typeof ServicesSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services/electrical': typeof ServicesElectricalRoute
  '/services/energy-audit': typeof ServicesEnergyAuditRoute
  '/services/energy-harvesting': typeof ServicesEnergyHarvestingRoute
  '/services/hvac': typeof ServicesHvacRoute
  '/services/lighting': typeof ServicesLightingRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/security': typeof ServicesSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services/electrical': typeof ServicesElectricalRoute
  '/services/energy-audit': typeof ServicesEnergyAuditRoute
  '/services/energy-harvesting': typeof ServicesEnergyHarvestingRoute
  '/services/hvac': typeof ServicesHvacRoute
  '/services/lighting': typeof ServicesLightingRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/security': typeof ServicesSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services/electrical'
    | '/services/energy-audit'
    | '/services/energy-harvesting'
    | '/services/hvac'
    | '/services/lighting'
    | '/services/plumbing'
    | '/services/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services/electrical'
    | '/services/energy-audit'
    | '/services/energy-harvesting'
    | '/services/hvac'
    | '/services/lighting'
    | '/services/plumbing'
    | '/services/security'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services/electrical'
    | '/services/energy-audit'
    | '/services/energy-harvesting'
    | '/services/hvac'
    | '/services/lighting'
    | '/services/plumbing'
    | '/services/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesElectricalRoute: typeof ServicesElectricalRoute
  ServicesEnergyAuditRoute: typeof ServicesEnergyAuditRoute
  ServicesEnergyHarvestingRoute: typeof ServicesEnergyHarvestingRoute
  ServicesHvacRoute: typeof ServicesHvacRoute
  ServicesLightingRoute: typeof ServicesLightingRoute
  ServicesPlumbingRoute: typeof ServicesPlumbingRoute
  ServicesSecurityRoute: typeof ServicesSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/security': {
      id: '/services/security'
      path: '/services/security'
      fullPath: '/services/security'
      preLoaderRoute: typeof ServicesSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/plumbing': {
      id: '/services/plumbing'
      path: '/services/plumbing'
      fullPath: '/services/plumbing'
      preLoaderRoute: typeof ServicesPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lighting': {
      id: '/services/lighting'
      path: '/services/lighting'
      fullPath: '/services/lighting'
      preLoaderRoute: typeof ServicesLightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hvac': {
      id: '/services/hvac'
      path: '/services/hvac'
      fullPath: '/services/hvac'
      preLoaderRoute: typeof ServicesHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/energy-harvesting': {
      id: '/services/energy-harvesting'
      path: '/services/energy-harvesting'
      fullPath: '/services/energy-harvesting'
      preLoaderRoute: typeof ServicesEnergyHarvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/energy-audit': {
      id: '/services/energy-audit'
      path: '/services/energy-audit'
      fullPath: '/services/energy-audit'
      preLoaderRoute: typeof ServicesEnergyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/electrical': {
      id: '/services/electrical'
      path: '/services/electrical'
      fullPath: '/services/electrical'
      preLoaderRoute: typeof ServicesElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesElectricalRoute: ServicesElectricalRoute,
  ServicesEnergyAuditRoute: ServicesEnergyAuditRoute,
  ServicesEnergyHarvestingRoute: ServicesEnergyHarvestingRoute,
  ServicesHvacRoute: ServicesHvacRoute,
  ServicesLightingRoute: ServicesLightingRoute,
  ServicesPlumbingRoute: ServicesPlumbingRoute,
  ServicesSecurityRoute: ServicesSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
